title: RSMP S2 Wiki
subtitle: 祭坛季 · 荒野生存 · 生活系统重做
description: RSMP S2 Minecraft 玩家手册
author: huohai114514
language: zh-CN
timezone: Asia/Shanghai

url: https://huohai114514.github.io/rsmp-s2-wiki
root: /rsmp-s2-wiki/
permalink: :title/
pretty_urls:
  trailing_index: false
  trailing_html: false

theme: rsmp-wiki


marked:
  prependRoot: true
  postAsset: true
  gfm: true

skip_render:
  - README.md
