menu:
  首页: /
  新手必读: /guide/
  合成配方: /recipes/
  炒菜: /cooking/
  农务果树: /farming/
  钓鱼: /fishing/
  日历: /calendar/
  星期怪物: /mobs-week/
  装备附魔: /enchant/
  精英Boss: /bosses/
  村民战利品: /villagers-loot/
  修复记录: /changelog/
